# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/chowd/ENEL 453/Labs/Lab_7/Lab_7/Lab_7.runs/synth_1/lab_7_top_level.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.statsThreshold 360
set_param chipscope.maxJobs 4
set_param synth.incrementalSynthesisCache C:/Users/chowd/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-16712-Anas/incrSyn
set_param checkpoint.writeSynthRtdsInDcp 1
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/chowd/ENEL 453/Labs/Lab_7/Lab_7/Lab_7.cache/wt} [current_project]
set_property parent.project_path {C:/Users/chowd/ENEL 453/Labs/Lab_7/Lab_7/Lab_7.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/chowd/ENEL 453/Labs/Lab_7/Lab_7/Lab_7.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/adc_processing.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/averager.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/averager_simple.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/bin_to_bcd.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/digit_multiplexor.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/downcounter.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/mux4_16_bits.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/output_mode_fsm.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/pwm.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/sawtooth_waveform.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/seven_segment_decoder.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/seven_segment_digit_selector.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/seven_segment_display_subsystem.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/lab_7_top_level.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/mux_data_en.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/adc_processing_pwm.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/pwm_ramp_adc_subsystem.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/r2r_adc_subsystem.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/sar_adc_subsystem.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/adc_processing_r2r.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/mux2_16_bits.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/Lab_7/Lab_7.srcs/sources_1/new/sar_pwm.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/Lab_7/Lab_7.srcs/sources_1/new/sar_processing.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/input_sync.sv}
  {C:/Users/chowd/ENEL 453/Labs/Lab_7/auto_cal.sv}
}
read_ip -quiet {{C:/Users/chowd/ENEL 453/Labs/Lab_7/Lab_7/Lab_7.srcs/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/chowd/ENEL 453/Labs/Lab_7/Lab_7/Lab_7.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/chowd/ENEL 453/Labs/Lab_7/Lab_7/Lab_7.gen/sources_1/ip/xadc_wiz_0/xadc_wiz_0.xdc}}]

read_ip -quiet {{c:/Users/chowd/ENEL 453/Labs/Lab_7/Lab_7/Lab_7.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{c:/Users/chowd/ENEL 453/Labs/Lab_7/Lab_7/Lab_7.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/chowd/ENEL 453/Labs/Lab_7/Lab_7/Lab_7.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/chowd/ENEL 453/Labs/Lab_7/Lab_7/Lab_7.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc}}]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/chowd/ENEL 453/Labs/Lab_7/Basys3_Lab_7.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/chowd/ENEL 453/Labs/Lab_7/Basys3_Lab_7.xdc}}]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental {C:/Users/chowd/ENEL 453/Labs/Lab_7/Lab_7/Lab_7.srcs/utils_1/imports/synth_1/lab_6_top_level.dcp}
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top lab_7_top_level -part xc7a35tcpg236-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef lab_7_top_level.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file lab_7_top_level_utilization_synth.rpt -pb lab_7_top_level_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
